### ISSUE TITLE
Call setgid, then setuid?

### ISSUE THREAD

**Issue by colemickens** [johnae/netns-exec#1]
I don't fully understand this, but saw this PR on Sway recently and thought it might apply to this code as well.

https://github.com/swaywm/sway/pull/5001

Do you need to call setgid then setuid as in the sway case?

**Comment by colemickens** [comment]
(By the  way, I didn't want to add more noise in the nixpkgs Issue, but a very big thank you for the detailed comments. I almost didn't ask a few times, but I'm glad I did, I learned a few things. Plus I'm always happy to see more Rust in the world for this kind of stuff! Thanks!)

**Comment by johnae** [comment]
Oh man. This was an oversight. Thank you for taking a look!

**Comment by johnae** [comment]
Again - thanks for letting me know. Fixed by https://github.com/johnae/netns-exec/commit/848636c0f5c1c99bc5f4922254f89c2e3ca6d473
