### ISSUE TITLE
Project Scope

### ISSUE THREAD

**Issue by colemickens** [johnae/netns-exec#2]
Hello again!

I was wondering a bit more about your use-case and if you have plans for this tool to be able to create the netns as well, or if you specifically only want this to be used for exec'ing in an exisitng netns?

I guess you have a systemd service that runs on boot, as root, that configures the netns?

**Comment by johnae** [comment]
Actually there's support for moving the wireguard interface into a network namespace (and creating it I think) in nixos (it's not documented when searching options though).
That plus some other things are outside my public nixos-configuration (I use the extra-builtins thing in nix to support encrypted "modules" basically).
Anyway, if you have a look here you'll see the option: https://github.com/NixOS/nixpkgs/blob/75b79b76d846a3b507e21fcc1a6d7949955c8344/nixos/modules/services/networking/wireguard.nix#L129

Ofc above assumes you're on NixOS...
It would be trivial to support creating the namespace within this tool ofc but it's not something I've given much thought.

**Comment by colemickens** [comment]
Thanks for that, I do use NixOS, but I'm sort of dreaming of a more sophisticated tool, for a wide userbase, that just takes a wg-quick profile as input, does the wg/netns bring-up **and** could provide better container-like safeguards around DNS leaks that the default netns protection doesn't provide.

One other question about your usage - does this imply that your WG is just always connected? Or can you leave the wg interface unconfigured, then run this tool, then configure/connect the wg interface?

**Comment by johnae** [comment]
Interesting. More containerization features might be interesting to implement, perhaps as several standalone binaries - it'd be easier to audit that way I believe when each binary has a single task.

I'm using firejail atm to contain firefox and chromium (thanks for putting together that wayland chromium package btw) but do feel that firejail, a setuid binary, has a very large surface area.

I could add namespace creation to this tool... How far would that take you?

**Comment by johnae** [comment]
When quickly looking at what `ip netns` does, it seems to do quite a bit actually when adding a new netns: https://github.com/shemminger/iproute2/blob/afa588490b7e87c5adfb05d5163074e20b6ff14a/ip/ipnetns.c#L635

I think, perhaps my tool should also do some mounting etc which may be what you're after wrt dns?

**Comment by colemickens** [comment]
I'm not sure. Part of my problem is that `ip netns exec` does bind mounting that can cause dns leaks. So, it's actually possible that by not mounting, those leaks might be avoided. I'd need to look into it more and I have some other things on my plate. For now this is plenty useful and/or I have my existing workflow.

**Comment by johnae** [comment]
Maybe. Otoh since we're leaving everything in place using my tool, `/etc/resolv.conf` would just be what's on the host. Anyway, I'll close this for now but feel free to open another issue if anything comes up!
